# Generated by Django 5.2 on 2025-04-11 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('video', models.FileField(upload_to='post_videos/')),
                ('audio', models.FileField(upload_to='post_audio/')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('jalali_updated_at', models.CharField(blank=True, editable=False, max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}')], verbose_name='تاریخ ویرایش')),
                ('jalali_created_at', models.CharField(blank=True, editable=False, max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}')], verbose_name='تاریخ ایجاد')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('jalali_created_at', models.CharField(blank=True, editable=False, max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}')], verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
