# Generated by Django 5.2 on 2025-04-08 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='jalali_created_at',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}')]),
        ),
    ]
